version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd $CODEBUILD_SRC_DIR/application
      - npm i -g zx
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/application
      - docker login --username $DOCKER_USER --password $DOCKER_TOKEN
      - npm run deploy
